### ISSUE TITLE
Graphic3d_RenderingParams class lacks data fields

### ISSUE THREAD

**Issue by shrdluk** [LaughlinResearch/pyOCCT#11]
## Expected Behavior

The [OCCT man page](https://www.opencascade.com/doc/occt-7.2.0/refman/html/class_graphic3d___rendering_params.html) and Graphic3d_RenderingParams.hxx include a number of data fields (Method, TransparencyMethod and others), which do not appear to be present in pyOCCT.

## Current Behavior

```
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OCCT.Graphic3d import Graphic3d_RenderingParams
>>> g = Graphic3d_RenderingParams ()
>>> g.Anaglyph
<class 'OCCT.Graphic3d.Graphic3d_RenderingParams.Anaglyph'>
>>> g.ResolutionRatio()
1.0
>>> g.Method
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OCCT.Graphic3d.Graphic3d_RenderingParams' object has no attribute 'Method'
>>> g.TransparencyMethod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OCCT.Graphic3d.Graphic3d_RenderingParams' object has no attribute 'TransparencyMethod'
>>> 
```
## Possible Solution

The data fields are not present in Graphic3d.cpp, as far as I can see.

## Steps to Reproduce (for bugs)

See Python session above.

## Context

This came up because I was trying to use Graphic3d_RenderingParams.Method to look at ray tracing. It's by no means important and I'm recording it here for completeness.

## Your Environment

* Version used: Current
* Operating System and version (desktop or mobile): Linux
* Link to your project:

## OpenCASCADE Bug
<!--- If a possible bug in OpenCASCADE library, please considering reporting it
<!--- to OpenCASCADE directory at https://tracker.dev.opencascade.org/

**Comment by trelau** [comment]
Thanks for reporting. The first time around I didn’t bind “data fields” although pybind11 supports it. I’m planning I’m doing this for OCCT 7.4.0. If you wanted to submit a PR with a unit test for these members that would be great. I’ll implement these manually to figure out how to best do it.

**Comment by trelau** [comment]
Fixed in https://github.com/LaughlinResearch/pyOCCT/commit/5a502d10fc2eca26e12c453e83a4d667b98ded63
