### ISSUE TITLE
CQ + LR = love ? ...

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [LaughlinResearch/pyOCCT#30]
I am curious if there is enough synergy / interest to join forces / reduce duplication:
https://github.com/CadQuery/cadquery/issues/310

CQ:
https://github.com/CadQuery/pywrap
https://github.com/CadQuery/OCP

LR:
https://github.com/LaughlinResearch/pyOCCT
https://github.com/LaughlinResearch/pyOCCT_binder

**Comment by trelau** [comment]
it's a great project. for now, i'm focusing on pyOCCT as a fun hobby, so staying focused on stabilizing it for multiple platforms and continuing to provide support for SMESH

**Comment by adam-urbanczyk** [comment]
Good to hear you are back @trelau . Let's see in the future for some synergy. I'm looking into wrapping the VTK support modules of OCCT, maybe it'll be interesting for you too.
