### ISSUE TITLE
Feature request: Support raytracing

### ISSUE THREAD

**Issue by frmdstryr** [LaughlinResearch/pyOCCT#42]
I'm not sure if raytracing works on other platforms or not but it currently doesn't in linux (I tried with a Windows VM and it didn't work there either).  

I believe this is an issue with occt, but pyOCCT will also need to add support as well (if occt gets it).

## Expected Behavior

In the cad assistant app rendering with raytracing works (notice shadows, antialiasing, and reflections). 

![raytracing](https://user-images.githubusercontent.com/380158/80895996-78188c80-8cb7-11ea-8790-9792815f8f50.png)

## Current Behavior

In DeclaraCAD these settings have no effect as the OpenGl_GraphicDriver says it's not supported.

![no-raytracing](https://user-images.githubusercontent.com/380158/80895998-84044e80-8cb7-11ea-9cf1-dff51171d48b.png)

## Possible Solution

From scanning the code it looks like OCCT requires the "USE_GLES2"  flag then it imports the gles2 headers and enables this block: https://github.com/Open-Cascade-SAS/OCCT/blob/master/src/OpenGl/OpenGl_Context.cxx#L1707

I'm trying to get it to work on linux, I've managed to build the `occt` package with gles2 support but still need to get pyOCCT to work with it.

**Comment by frmdstryr** [comment]
Heh, so this has nothing to do with the GLES2 flag...  

The problem was that pybind is making a copy of the returned object instead of the reference so the changes to the rendering params don't update the actual views parameters!

![declaracad-raytracing](https://user-images.githubusercontent.com/380158/81219182-667fff00-8fad-11ea-881f-ddf10737a985.png)


```c
# Return ref
+patch V3d: &V3d_View::ChangeRenderingParams-->&V3d_View::ChangeRenderingParams, py::return_value_policy::reference
```

Think binder should use `py::return_value_policy::reference` for anything that returns a non-const reference?

**Comment by frmdstryr** [comment]
I think detecting when a ref should be used needs to be added into the binder... a lot of methods return references (eg https://dev.opencascade.org/doc/refman/html/class_prs3d___drawer.html) that return copies and do nothing when modified from python (currently need to save a ref to the copy then reassign it). 

I'll try to to a PR.

**Comment by trelau** [comment]
@frmdstryr had that in mind when making this ticket for ref https://github.com/LaughlinResearch/pyOCCT_binder/issues/14
